version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        versions: [">=3.5.x"]
      - dependency-name: "org.springframework:*"
        versions: [">=6.2.x"]
      - dependency-name: "jakarta.servlet:jakarta.servlet-api"
        versions: [ ">=6.0.x" ]